CREATE TABLE Users (
    USER_ID int(11) NOT NULL AUTO_INCREMENT,
    EMAIL varchar(50) NOT NULL,
    USER_PASSWORD varchar(50) NOT NULL
);
CREATE TABLE Note(
	NOTE_ID int(11) NOT NULL AUTO_INCREMENT,
	USER_ID int(11) NOT NULL,
	TITTLE varchar(11),
	TEXT varchar(350) NOT NULL,
);

