version: '3.3'
services:
  got-that-note-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'got-that-note-db-MySql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./sql-script/createDb.sql:/docker-entrypoint-initdb.d/createDb.sql
    expose:
      - '3306'
volumes:
  got-that-note-db:
