version: '3.3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: notesDb-MongoDB
    volumes:
      - ./mongo-script/createdb.mongodb:/docker-entrypoint-initdb.d/createdb.mongodb
    ports:
      - '27017:27017'
volumes:
  mongodb: null
